---
# handlers file for unitedtraders.nginxauthdaemon
- name: "restart {{ nginxauth_service }}"
  service: name={{ nginxauth_service }} state=restarted

- name: reload systemd units
  command: systemctl daemon-reload
  notify: "restart {{ nginxauth_service }}"
